import { cookies } from 'next/headers';
import { getTokens } from 'next-firebase-auth-edge';
import { firebaseClientConfig, firebaseServerConfig } from '../config/firebase';
import { AuthProvider } from '../context/AuthContext';
import '@/styles/tailwind.css'


export default async function RootLayout({ children }) {
  const cookiesHeader = cookies();
  const tokens = await getTokens(cookiesHeader, {
    apiKey: firebaseClientConfig.apiKey,
    cookieName: firebaseServerConfig.cookieName,
    cookieSignatureKeys: firebaseServerConfig.cookieSignatureKeys,
    serviceAccount: firebaseServerConfig.serviceAccount,
  });

  const user = tokens ? tokens.decodedToken : null;
  //let events = await getEvents()

  return (
    <html
      lang="fr"
      className="text-zinc-950 antialiased lg:bg-zinc-100 dark:bg-zinc-900 dark:text-white dark:lg:bg-zinc-950"
    >
      <head>
        <title>FESTI</title>
        <meta name="description" content="Generated by 3 GOATS" />
      </head>

      <body>
        <AuthProvider initialUser={user}>
            {children}
        </AuthProvider>
      </body>
    </html>
  );
}