import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import ClientLayout from './ClientLayout';
import '@/styles/tailwind.css'
import Providers from '@/components/Providers';
import { ReCaptchaProvider } from 'next-recaptcha-v3';



export default async function RootLayout({ children }) {

  const locale = await getLocale();

  // Providing all messages to the client side is the easiest way to get started
  const messages = await getMessages();


  return (
    <html
      lang={locale}
      className="h-full bg-gray-50 text-zinc-950 antialiased lg:bg-zinc-100 dark:bg-zinc-900 dark:text-white dark:lg:bg-zinc-950"
    >
      <head>
        <title>FESTI</title>
        <meta name="description" content="Generated by 3 GOATS" />
      </head>

      <body className="h-full">
        <NextIntlClientProvider messages={messages}>
          <Providers>
            <ClientLayout>
              <ReCaptchaProvider reCaptchaKey={process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY}>
                {children}
              </ReCaptchaProvider>
            </ClientLayout>
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}